site_name: santa-lang
repo_url: https://github.com/eddmann/santa-lang
site_description: An functional, C-like programming language for solving Advent of Code puzzles.
site_author: Edd Mann
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate
nav:
  - Home: index.md
  - Language: language.md
  - Builtins: builtins.md
  - Runner: runner.md
  - Formatter: formatter.md
  - Reindeer:
      - Overview: reindeer/index.md
      - Comet (Rust): reindeer/comet.md
      - Blitzen (Rust): reindeer/blitzen.md
      - Dasher (Rust): reindeer/dasher.md
      - Donner (Kotlin): reindeer/donner.md
      - Prancer (TypeScript): reindeer/prancer.md
  - Runtimes:
      - CLI: cli.md
      - Web: web.md
      - Lambda: lambda.md
      - PHP Extension: php-ext.md
      - Jupyter Kernel: jupyter-kernel.md
  - Examples: examples.md
extra_javascript:
  - assets/runner.js
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: false
  - attr_list
  - md_in_html
